<h1>Grip@ The Sparks Foundation<br><br>
Data Science and Business Analytics Intern</h1>

## Sanskriti Bansal

 <h2>Prediction Using Supervised Learning</h2>

### Importing libraries

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import re
import string

### Importing Datasets

In [7]:
df_fake = pd.read_csv("C:\\Users\\Sanskriti\\Downloads\\Fake.csv")
df_true = pd.read_csv("C:\\Users\\Sanskriti\\Downloads\\True.csv")

In [8]:
df_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [9]:
df_true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [10]:
df_fake.shape

(23481, 4)

In [11]:
df_true.shape

(21417, 4)

### Data Preprocessing

In [12]:
# inserting target column such that fake news=0, true news=1
df_fake["class"] = 0
df_true["class"] = 1

In [13]:
# merging 2 datasets (fake and true news) to 1 dataset
df_merge = pd.concat([df_fake, df_true], axis = 0)
df_merge.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0

In [14]:
df_merge.shape

(44898, 5)

In [15]:
# Dropping unwanted columns

df = df_merge.drop(["title", "subject", "date"], axis = 1)
df.head()

text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [16]:
# Checking for null values

df.isnull().sum()

text     0
class    0
dtype: int64

In [17]:
# Removing unnecessary characters

def word_drop(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W", " ", text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [18]:
df["text"] = df["text"].apply(word_drop)

In [19]:
df.head()

text  class
0  donald trump just couldn t wish all americans ...      0
1  house intelligence committee chairman devin nu...      0
2  on friday  it was revealed that former milwauk...      0
3  on christmas day  donald trump announced that ...      0
4  pope francis used his annual christmas day mes...      0

In [20]:
df.shape

(44898, 2)

In [21]:
x = df["text"]
y = df["class"]

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25)

In [23]:
# converting text into vector format

from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

## Implementing Machine Learning Models

### Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(xv_train, y_train)
y_pred_lr = lr.predict(xv_test)

In [25]:
print(".........Logistic Regression Model.........\n")
print("1.) Accuracy: ", accuracy_score(y_test, y_pred_lr))
print("\n2.) Classification Report:\n\n", classification_report(y_test, y_pred_lr))
print("\n3.) Confusion Matrix:\n\n", confusion_matrix(y_test, y_pred_lr))

.........Logistic Regression Model.........

1.) Accuracy:  0.9851224944320712

2.) Classification Report:

               precision    recall  f1-score   support

           0       0.99      0.98      0.99      5868
           1       0.98      0.99      0.98      5357

    accuracy                           0.99     11225
   macro avg       0.98      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225


3.) Confusion Matrix:

 [[5762  106]
 [  61 5296]]


### Decision Tree Model

In [26]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(xv_train, y_train)
y_pred_dt = dt.predict(xv_test)

In [27]:
print(".........Decision Tree Model.........\n")
print("1.) Accuracy: ", accuracy_score(y_test, y_pred_dt))
print("\n2.) Classification Report:\n\n", classification_report(y_test, y_pred_dt))
print("\n3.) Confusion Matrix:\n\n", confusion_matrix(y_test, y_pred_dt))

.........Decision Tree Model.........

1.) Accuracy:  0.9955456570155902

2.) Classification Report:

               precision    recall  f1-score   support

           0       1.00      1.00      1.00      5868
           1       1.00      1.00      1.00      5357

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225


3.) Confusion Matrix:

 [[5843   25]
 [  25 5332]]


### Random Forest classification

In [28]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 100)
rfc.fit(xv_train, y_train)
y_pred_rfc = rfc.predict(xv_test)

In [29]:
print(".........Random Forest Classification Model.........\n")
print("1.) Accuracy: ", accuracy_score(y_test, y_pred_rfc))
print("\n2.) Classification Report:\n\n", classification_report(y_test, y_pred_rfc))
print("\n3.) Confusion Matrix:\n\n", confusion_matrix(y_test, y_pred_rfc))

.........Random Forest Classification Model.........

1.) Accuracy:  0.9880623608017818

2.) Classification Report:

               precision    recall  f1-score   support

           0       0.99      0.99      0.99      5868
           1       0.99      0.99      0.99      5357

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225


3.) Confusion Matrix:

 [[5792   76]
 [  58 5299]]


## Comparison

In [47]:
print(" _______________________________________________")
print("|\tModel\t\t|\tAccuracy\t|")
print("|_______________________|_______________________|")
print("|                       |                       |")
print("|  Logistic Regression  |  ", accuracy_score(y_test, y_pred_lr)," |")
print("|  Random Forest        |  ", accuracy_score(y_test, y_pred_rfc)," |")
print("|  Decision Tree        |  ", accuracy_score(y_test, y_pred_dt)," |")
print("|_______________________|_______________________|")

 _______________________________________________
|	Model		|	Accuracy	|
|_______________________|_______________________|
|                       |                       |
|  Logistic Regression  |   0.9851224944320712  |
|  Random Forest        |   0.9880623608017818  |
|  Decision Tree        |   0.9955456570155902  |
|_______________________|_______________________|


<b>Analysis</b><br><br>Based on accuracy, Decision Tree Model has the highest accuracy and Logistic Regression Model has lowest accuracy. Therefore, for this dataset on fake news detection, Decision Tree has the best performance with 99.5% accurate predictions.